<?php

namespace GestionEntreprise\ParametrageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriePrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePrestationRepository extends EntityRepository
{
	public function getByTypeClient(TypeClient $typeClient)
    {
        $qb = $this->createQueryBuilder('cpt');

        // On fait une jointure sur la table des tags, avec pour alias « cpt ».
        $qb ->where('cpt.typeClient = :typeClient')
			->setParameter('typeClient', $typeClient)
            ->orderBy('cpt.libelle');
			
		// Enfin, on retourne le résultat.
        return $qb->getQuery()->getResult();
    }
}